Improvements in doctor.js
jain-rishabh-21/DoctorVerse pull request #56
Opened 2023-05-28 11:41 UTC by Naman1729

This more modifies the file:
- server/model/doctor.js

This PR resolves #55 

- [x] Adding Language: Preferred language for effective patient-doctor communication.
- [x] Adding qualityAssurance: To providing high-quality care.
- [x] Adding emailAddress: To connect Doctor and Patient.
- [x] Adding clinicHygiene: Rating of hygiene of clinic.
- [x] Adding openTime: Opening time of clinic.
- [x] Adding closeTime: Closing time of clinic.

2023-05-29 09:05 UTC, apeksha235 requested changes
I have asked you to make a few changes, do that and let me know.

2023-05-29 09:05 UTC, apeksha235 commented on server/model/doctor.js
> +    Language: {
- avoid using capital letters to start a variable, just change this. rest all seems great

2023-05-29 09:05 UTC, apeksha235 commented on server/model/doctor.js
>      placeOfPractice:{
- set rest of the parameters as required as well.

2023-05-29 18:17 UTC, jain-rishabh-21 commented
I suggest using "prettier" vscode extension for formatting! 
Just install prettier and then auto format the file.
@Naman1729

2023-05-30 15:05 UTC, apeksha235 approved these changes
It's good to go!

2023-05-30 15:06 UTC, merged

2023-06-23 20:55 UTC, Naman1729 commented
Hey @apeksha235, Please add labels of GSSOC'23.